### ISSUE TITLE
64-bit VFP

### ISSUE THREAD

**Issue by joec4281** [EricLendvai/Harbour_VFP#1]
You may or may not be aware, but there is a 64-bit version of VFP.

http://www.baiyujia.com/vfpadvanced/f_vfpa_about.asp

I learned about it at Virtual Fox Fest last fall.

Joe

**Comment by EricLendvai** [comment]
Thanks Joe, but I don't think it is open source and all platforms.
Please correct me if I am wrong.
One of the major advantages for now of VFP is its DBF and in-memory tables (cursors) SQL engine.
At least with the new Harbour ORM we can do SQL against PostgreSQL and MySQL easily and I added an simple method to create and manage cursors.
